name: GitHub Actions Demo
on: workflow_dispatch
jobs:
  build_hello:
    runs-on: ubuntu-18.04
    steps:
      - name: Ensure all dependencies are installed
        run: sudo apt-get install -y gcc make tar
      - name: Do the build
        run: |
          cd src
          make dist
