name: GitHub Actions Demo
on: workflow_dispatch
jobs:
  build_hello:
    runs-on: ubuntu-18.04
    steps:
      - name: Ensure all dependencies are installed
        run: sudo apt-get install -y gcc make tar
        
      - name: Checkout repository content
        uses: actions/checkout@v2
        
      - name: look aroud
        run: |
          (
          pwd
          ls -la
          ls -la ..
          ls -la ../..
          ) 2>&1 | while read l; do echo "::notice::$l"; done
          
      # - name: Do the build
      #   working-directory: src
      #   run: |
      #     make dist
