name: GitHub Actions Demo
on: workflow_dispatch
jobs:
  build_hello:
    runs-on: ubuntu-18.04
    steps:
      - name: Ensure all dependencies are installed
        run: sudo apt-get install -y gcc make tar
      - name: look aroud
        run: go.sh
          
      # - name: Do the build
      #   working-directory: src
      #   run: |
      #     make dist
