name: GitHub Actions Demo
on: workflow_dispatch
jobs:
  build_hello:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
        
      - name: Do the thing
        run:
          mkdir artifacts
          (
          bash go.sh
          echo "$?" > status.txt
          ) 2>&1 | tee artifacts/build.log | \
          while read l; do
            echo "::notice::$l"
          done
          exit `cat status.txt`
